

version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js:
  - 12
cache:
  - npm
  - pip

script:
  - echo "helloworld"
  - hostname
  - cd .travis
  - wget  https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/.travis/merge_if_success.sh
  - bash merge_if_success.sh
  - cd -
